[package]
name = "pixel_proc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.22", features = ["full", "extra-traits"] }
quote = "1.0.6"